# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-45060-nikhil/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tsbg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/ip/prim/rtl
    /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/dv/sv/dv_utils
  } -define MAIN_CORE_IBEX {
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_pkg.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_pkg.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_alu.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_branch_predict.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_compressed_decoder.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_controller.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_core.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_counter.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_cs_registers.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_csr.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_decoder.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_dummy_instr.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_ex_block.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_fetch_fifo.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_icache.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_id_stage.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_if_stage.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_load_store_unit.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_lockstep.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_multdiv_fast.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_multdiv_slow.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_pmp.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_prefetch_buffer.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_register_file_ff.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_register_file_fpga.sv
      /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_top.sv
      /home/nikhil/vicuna-build/vicuna/ibex/rtl/ibex_wb_stage.sv
      /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
      /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_28_22_dec.sv
      /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_28_22_enc.sv
      /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_dec.sv
      /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_enc.sv
      /home/nikhil/vicuna-build/vicuna/demo/rtl/ram.sv
      /home/nikhil/vicuna-build/vicuna/demo/rtl/uart_rx.sv
      /home/nikhil/vicuna-build/vicuna/demo/rtl/uart_tx.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_alu.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_cache.sv
      /home/nikhil/Nikhil/ElectronicsDev/RISC-V/Vicuna/tests/vector_add/synth/vproc_config.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_core.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_decoder.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_dispatcher.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_elem.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_lsu.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_mul.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_mul_block.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_pending_wr.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_pipeline.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_pipeline_wrapper.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_queue.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_result.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_sld.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_top.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_unit_mux.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_unit_wrapper.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_vreg_wr_mux.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_vregfile.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_vregpack.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_vregunpack.sv
      /home/nikhil/vicuna-build/vicuna/rtl/vproc_xif.sv
      /home/nikhil/vicuna-build/vicuna/demo/rtl/demo_top.sv
    }
      rt::read_verilog -include {
    /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/ip/prim/rtl
    /home/nikhil/vicuna-build/vicuna/ibex/vendor/lowrisc_ip/dv/sv/dv_utils
  } -define MAIN_CORE_IBEX /home/nikhil/vicuna-build/vicuna/ibex/syn/rtl/prim_clock_gating.v
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top demo_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-45060-nikhil/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -param {
  { RAM_FPATH {"/home/nikhil/Nikhil/ElectronicsDev/RISC-V/Vicuna/tests/vector_add/vector_addition.vmem"} }
  { DIFF_CLK 0 }
  { SYSCLK_PER 10.0 }
} -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
